# Generated by Django 2.0.2 on 2018-04-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
    ]
