# Generated by Django 2.0.4 on 2018-04-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_bookmark_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='category',
            field=models.CharField(blank=True, choices=[('FI', 'Film'), ('GA', 'Gaming'), ('MU', 'Music'), ('TE', 'Tech')], max_length=100, null=True, verbose_name='Category'),
        ),
    ]
