# Generated by Django 2.0.4 on 2018-04-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0007_auto_20180412_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='category',
            field=models.CharField(choices=[('Film', 'Film'), ('Gaming', 'Gaming'), ('Music', 'Music'), ('Tech', 'Tech')], max_length=50, null=True, verbose_name='Category'),
        ),
    ]
